### ISSUE TITLE
 ValueError: '/data/data/org.test.myapp/files/app/libs/garden/garden.zbarcam' is not a package

### ISSUE THREAD

**Issue by wangyuncong123** [kivy-garden/zbarcam#13]
garden.zbarcam is not a package.

my buildozer.spec:
```
# (list) Garden requirements
garden_requirements = xcamera,zbarcam
```

**Comment by AndreMiras** [comment]
The `garden.zbarcam' is not a package` error should be fixed with with last release.
@vmisiko the last error you are sharing is not related to this issue, but to https://github.com/kivy-garden/zbarcam/issues/12 and https://github.com/kivy-garden/zbarcam/issues/16
