### ISSUE TITLE
JavaException: JVM exception occurred: Fail to connect to camera service

### ISSUE THREAD

**Issue by surbhicis** [kivy-garden/zbarcam#16]
JavaException: JVM exception occurred: Fail to connect to camera service

![Screenshot from 2019-07-30 18-13-31](https://user-images.githubusercontent.com/24718338/62130288-550b1780-b2f6-11e9-9dbb-283202018139.png)

**Comment by AndreMiras** [comment]
Hi @surbhicis thanks for the bug report. This is probably related to #12 could you verify?
