### ISSUE TITLE
Can not run with latest kivy garden

### ISSUE THREAD

**Issue by wangkui0508** [kivy-garden/zbarcam#28]
After I installed the latest kivy and kivy garden, I met following error when start zbarcam demo:

```
[ERROR  ] 
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/kivy/lang/parser.py", line 474, in execute_directives
    mod = __import__(package)
ModuleNotFoundError: No module named 'kivy_garden.xcamera'
```
 After Changing the first line of src/kivy_garden/zbarcam/zbarcam.kv into:
```
#:import XCamera kivy.garden.xcamera.XCamera
```
(note it's kivy.garden not kivy_garden)
And then it works.

So I think it is a typo of zbarcam.kv

**Comment by AndreMiras** [comment]
How did you install zbarcam and xcamera? The recommended method is no longer via `garden install`, but pip install. Try `garden uninstall` both modules and install zbarcam using `pip install zbarcam` as described in the REAME.md

**Comment by wangkui0508** [comment]
Yes I installed xcamera using garden install. I follow your method and re-install xcamera with pip. Now it works fine. Thank you very much!
