### ISSUE TITLE
cannot import zbarcam from kivy_garden

### ISSUE THREAD

**Issue by wolfc01** [kivy-garden/zbarcam#29]
Hi

On android, I cannot import the zbarcam from kivy garden.

I have added Kivy-Garden to the requirements but no avail.
requirements =
    android,
    kivy==1.11.1,
    libiconv,
    libzbar,
    Pillow==7.0.0,
    python3,
    pyzbar==0.1.8,
    xcamera==2019.928,
    Kivy-Garden==0.1.4

How to troubleshoot this?
Best regards
Carl.

**Comment by tshirtman** [comment]
you don't need to add kivy-garden, but to add `kivy-garden.zbarcam`.

https://github.com/AndreMiras/PyWallet/blob/develop/buildozer.spec#L62

**Comment by wolfc01** [comment]
Hi tshirtman,

thanks again for your help.

Best regards
Carl
