### ISSUE TITLE
Issue trying to install libzbar-dev

### ISSUE THREAD

**Issue by fitoprincipe** [kivy-garden/zbarcam#4]
I am trying to install it in a 32-bits notebook with ubuntu 14.04, but I can't install libzbar-dev.

> libgraphviz-dev : Depends on: libgvc6-plugins-gtk (= 2.36.0-0ubuntu3.2) but 2.36.0-0ubuntu3.1 will be installed

and when I go `sudo apt-get install libgvc6-plugins-gtk=2.36.0-0ubuntu3.2` says

> Version «2.36.0-0ubuntu3.2» was not found for «libgvc6-plugins-gtk»

Any idea??

**Comment by AndreMiras** [comment]
Too bad Ubuntu 16.04 is also broken here. But that's definitely an upstream issue, not something `zbarcam` can fix.
I'm running 18.04 and don't have this issue
