### ISSUE TITLE
Invalid code types

### ISSUE THREAD

**Issue by FrCln** [kivy-garden/zbarcam#63]
When running the example on Android, this error is shown in logs (app fails to start):
ValueError: Invalid code types: [<ZBarSymbol.QRCODE: 64>, <ZBarSymbol.EAN13: 13>]. Available code types: {'NONE', 'CODE128', 'I25', 'EAN2', 'EAN5', 'EAN8', 'QRCODE', 'UPCE', 'UPCA', 'PARTIAL', 'DATABAR', 'CODE93', 'DATABAR_EXP', 'ISBN10', 'ISBN13', 'PDF417', 'CODABAR', 'CODE39', 'EAN13', 'COMPOSITE'}

**Comment by FrCln** [comment]
I took this example from `master` branch: [src/main.py](https://github.com/kivy-garden/zbarcam/blob/master/src/main.py)
```python
code_types: ZBarSymbol.QRCODE, ZBarSymbol.EAN13
```
But I used the library from `develop` branch. There should be another version: [src/main.py](https://github.com/kivy-garden/zbarcam/blob/develop/src/main.py).
```python
code_types: 'QRCODE', 'EAN13'
```

**Comment by AndreMiras** [comment]
Ah yeah I should make a release
